version: 2
updates:
  - commit-message:
      include: "scope"
      prefix: "chore"
    directory: "/"
    open-pull-requests-limit: 10
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      time: "10:00"
    versioning-strategy: "increase"
